#!/usr/bin/env python3
"""
tree-stats.py — Out-degree + depth distribution for the ecosystem tree.

Uses the same scanner as `generator/generate-ecosystem.py`, so the numbers
reflect exactly what the canvas sees.

Usage:
    python3 tools/tree-stats.py [--config PATH] [--output PATH]

Default output: research/tree-stats-YYYY-MM-DD.md
"""

import argparse
import datetime
import statistics
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).parent.resolve()
PROJECT_ROOT = SCRIPT_DIR.parent
GENERATOR_DIR = PROJECT_ROOT / "generator"
RESEARCH_DIR = PROJECT_ROOT / "research"

sys.path.insert(0, str(GENERATOR_DIR))
import importlib.util  # noqa: E402
from config import ConfigError  # noqa: E402

# The generator filename has a dash, which Python imports don't tolerate — load
# the module by spec instead.
gen_spec = importlib.util.spec_from_file_location(
    "gen", GENERATOR_DIR / "generate-ecosystem.py"
)
gen = importlib.util.module_from_spec(gen_spec)
gen_spec.loader.exec_module(gen)


def walk_directories(node, depth=0):
    """Yield (depth, child_count, path, name) for every directory node."""
    if node.get("type") != "directory":
        return
    children = node.get("children", [])
    yield depth, len(children), node.get("path", ""), node.get("name", "")
    for child in children:
        yield from walk_directories(child, depth + 1)


def percentile(sorted_values, p):
    if not sorted_values:
        return 0
    k = (len(sorted_values) - 1) * p / 100
    f = int(k)
    c = min(f + 1, len(sorted_values) - 1)
    if f == c:
        return sorted_values[f]
    return sorted_values[f] + (sorted_values[c] - sorted_values[f]) * (k - f)


def histogram(values, buckets):
    """buckets is a list of (label, low, high) tuples. high is inclusive."""
    counts = {label: 0 for label, _, _ in buckets}
    for v in values:
        for label, low, high in buckets:
            if low <= v <= high:
                counts[label] += 1
                break
    return counts


def make_bar(count, max_count, width=40):
    if max_count == 0:
        return ""
    filled = int((count / max_count) * width)
    return "█" * filled


def render_report(tree, generated_at):
    all_dirs = list(walk_directories(tree))
    child_counts = [c for _, c, _, _ in all_dirs]
    depths = [d for d, _, _, _ in all_dirs]

    total_dirs = len(all_dirs)
    total_children = sum(child_counts)
    sorted_counts = sorted(child_counts)

    mean = statistics.mean(child_counts) if child_counts else 0
    median = statistics.median(child_counts) if child_counts else 0
    p90 = percentile(sorted_counts, 90)
    p95 = percentile(sorted_counts, 95)
    p99 = percentile(sorted_counts, 99)
    maxv = max(child_counts) if child_counts else 0

    max_depth = max(depths) if depths else 0

    buckets = [
        ("    0    ", 0, 0),
        ("    1-5  ", 1, 5),
        ("    6-10 ", 6, 10),
        ("   11-20 ", 11, 20),
        ("   21-50 ", 21, 50),
        ("   51-100", 51, 100),
        ("  101-200", 101, 200),
        ("  201+   ", 201, 10**9),
    ]
    hist = histogram(child_counts, buckets)
    max_bar = max(hist.values()) if hist else 1

    top10 = sorted(all_dirs, key=lambda t: t[1], reverse=True)[:10]

    depth_hist = {}
    for d in depths:
        depth_hist[d] = depth_hist.get(d, 0) + 1

    lines = []
    lines.append(f"# Tree Stats — {generated_at.strftime('%Y-%m-%d')}")
    lines.append("")
    lines.append(
        "Generated by `tools/tree-stats.py`. Reflects exactly what the canvas "
        "sees (same scanner as `generator/generate-ecosystem.py`)."
    )
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total directories: **{total_dirs}**")
    lines.append(f"- Total children across all directories: **{total_children}**")
    lines.append(f"- Max depth: **{max_depth}**")
    lines.append(f"- Mean children per directory: **{mean:.2f}**")
    lines.append(f"- Median children per directory: **{median:.0f}**")
    lines.append(f"- 90th percentile: **{p90:.0f}**")
    lines.append(f"- 95th percentile: **{p95:.0f}**")
    lines.append(f"- 99th percentile: **{p99:.0f}**")
    lines.append(f"- Max: **{maxv}**")
    lines.append("")
    lines.append("## Histogram — children count → number of directories")
    lines.append("")
    lines.append("```")
    for label, _, _ in buckets:
        count = hist[label]
        bar = make_bar(count, max_bar)
        lines.append(f"{label}: {bar} {count}")
    lines.append("```")
    lines.append("")
    lines.append("## Depth distribution")
    lines.append("")
    lines.append("```")
    max_depth_count = max(depth_hist.values()) if depth_hist else 1
    for d in sorted(depth_hist):
        bar = make_bar(depth_hist[d], max_depth_count, width=30)
        lines.append(f"depth {d:>2}: {bar} {depth_hist[d]}")
    lines.append("```")
    lines.append("")
    lines.append("## Top 10 largest directories (by direct children)")
    lines.append("")
    for depth, count, path, name in top10:
        short = path.replace(str(Path.home()), "~")
        lines.append(f"- **{count}** — `{short}` (depth {depth})")
    lines.append("")
    lines.append("## Interpretation for gradient-pack layout")
    lines.append("")
    lines.append(
        "The layout uses `d3.pack` — one rule applied recursively, no "
        "thresholds. This report is grounding data (what do real directories "
        "look like?), not threshold calibration."
    )
    lines.append("")
    lines.append(
        "- Most directories are small (median ≈ few children). These pack as "
        "loose arrangements — visually fan-like."
    )
    lines.append(
        "- A small tail of directories has many children (99th percentile "
        f"≈ {p99:.0f}, max {maxv}). These pack tightly as dense organic "
        "clusters inside their parent's circle."
    )
    lines.append(
        "- The same `pack` call produces both — no switch, no classifier. "
        "Size is signal; density is consequence."
    )
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Ecosystem tree stats.")
    parser.add_argument("--config", help="Path to config.json.")
    parser.add_argument("--output", help="Output markdown path.")
    args = parser.parse_args()

    try:
        cfg = gen.load_config(args.config)
    except ConfigError as e:
        print(f"✗ {e}", file=sys.stderr)
        sys.exit(1)

    print("Scanning ecosystem (same pipeline as canvas generator)...", file=sys.stderr)
    cross_links = []
    tree = gen.build_ecosystem_tree(cfg, cross_links)

    generated_at = datetime.datetime.now()
    report = render_report(tree, generated_at)

    if args.output:
        out = Path(args.output)
    else:
        RESEARCH_DIR.mkdir(exist_ok=True)
        out = RESEARCH_DIR / f"tree-stats-{generated_at.strftime('%Y-%m-%d')}.md"

    out.write_text(report, encoding="utf-8")
    print(f"Wrote {out}", file=sys.stderr)
    print("", file=sys.stderr)
    # Also print the summary section to stdout for immediate visibility.
    for line in report.splitlines():
        print(line)


if __name__ == "__main__":
    main()
